apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-dep
  labels:
    app: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
        - name: back-con
          image: docker.io/parshant09/l-backend:latest
          env:
            - name: MONGO_URI
              value: "mongodb://admin:admin%40123@mongo-ser:27017/huxnStore?authSource=admin"
 
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: back-ser
spec:
  selector:
    app: back
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
