apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: mongo-con
          image: docker.io/mongo:7.0
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "admin@123"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: dbvol
              mountPath: /data/db
      volumes:
        - name: dbvol
          persistentVolumeClaim:
            claimName: dbvol

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-ser
spec:
  selector:
    app: db
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
