apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbvoll
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /kok
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbvol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
